# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'
    addToPath: true

- script: |
    gem install bundler -v 1.17.3
    gem install middleman 
  displayName: 'install bundler'

- script: |
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: |
    bundle exec middleman build --clean
  displayName: 'middleman build'    

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/build/'
    artifactName: ApiDocs