# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- master

schedules:
- cron: "30 0 * * 1-5"
  displayName: 12:30am build, Mon-Fri
  branches:
    include:
    - master
  always: true

pool:
  vmImage: ubuntu-latest

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '2.7.6'
    addToPath: true

- script: |
    gem install bundler -v 1.15.4
    gem install middleman 
    bundle _1.15.4_ install --retry=3 --jobs=4
    bundle _1.15.4_ exec middleman build --clean
  displayName: 'build the site'    
  workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/build/'
    artifactName: ApiDocs